# Workflow to upload next.js integration test results to KV for https://areweturboyet.com/
# This workflow assumes the `next-integration-test` workflow has been executed
# and test reports have been uploaded to the `test-results` artifact.
name: Upload Turbopack tests manifest to areweturboyet.com

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:
    inputs:
      version:
        description: Next.js version, sha, branch to test
        type: string
        default: 'canary'

jobs:
  upload_test_results:
    name: Upload test results
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_LTS_VERSION }}
          check-latest: true

      - name: Checkout
        uses: actions/checkout@v4

      - run: corepack enable

      - name: Install dependencies
        shell: bash
        run: pnpm i

      - name: 'Upload results to "Are We Turbo Yet" KV'
        env:
          TURBOYET_KV_REST_API_URL: ${{ secrets.TURBOYET_KV_REST_API_URL }}
          TURBOYET_KV_REST_API_TOKEN: ${{ secrets.TURBOYET_KV_REST_API_TOKEN }}
        uses: ./.github/actions/upload-turboyet-data
            - الاسم: إعداد بيئة Node.js
  الاستخدامات: actions/setup-node@v4.1.0
  مع:
    # تعيين دائمًا المصادقة في npmrc.
    always-auth: # اختياري، الافتراضي هو false
    # مواصفات الإصدار المراد استخدامه. الأمثلة: 12.x، 10.15.1، >=10.15.0.
    إصدار العقدة: # اختياري
    # ملف يحتوي على مواصفات الإصدار المراد استخدامه. الأمثلة: package.json، و.nvmrc، و.node-version، و.tool-versions.
    ملف إصدار العقدة: # اختياري
    # الهندسة المعمارية المستهدفة التي يجب على Node استخدامها. الأمثلة: x86، x64. سيتم استخدام هندسة النظام بشكل افتراضي.
    الهندسة المعمارية: # اختياري
    # قم بتعيين هذا الخيار إذا كنت تريد أن يتحقق الإجراء من أحدث إصدار متوفر يلبي مواصفات الإصدار.
    التحقق-الأحدث: # اختياري
    # سجل اختياري لإعداده للمصادقة. سيتم تعيين السجل في ملف .npmrc و.yarnrc على مستوى المشروع، وإعداد المصادقة للقراءة من env.NODE_AUTH_TOKEN.
    عنوان URL للسجل: # اختياري
    # نطاق اختياري للمصادقة على السجلات المحددة النطاق. سيتم الرجوع إلى مالك المستودع عند استخدام سجل حزم GitHub (https://npm.pkg.github.com/).
    النطاق: # اختياري
    # يستخدم لسحب توزيعات العقد من إصدارات العقد. نظرًا لوجود قيمة افتراضية، لا يتم توفير هذه القيمة عادةً بواسطة المستخدم. عند تشغيل هذا الإجراء على github.com، تكون القيمة الافتراضية كافية. عند التشغيل على GHES، يمكنك تمرير رمز وصول شخصي إلى github.com إذا كنت تواجه قيودًا على المعدل.
    الرمز المميز: # اختياري، الافتراضي هو ${{ github.server_url == 'https://github.com' && github.token || '' }}
    # يستخدم لتحديد مدير الحزم للتخزين المؤقت في الدليل الافتراضي. القيم المدعومة: npm، yarn، pnpm.
    ذاكرة التخزين المؤقت: # اختياري
    # يستخدم لتحديد المسار إلى ملف التبعية: package-lock.json، yarn.lock، وما إلى ذلك. يدعم الأحرف البدل أو قائمة بأسماء الملفات لتخزين التبعيات المتعددة في ذاكرة التخزين المؤقت.
    مسار التبعية للذاكرة المؤقتة: # اختياري
          
